### ISSUE TITLE
Should the default values for `target` and `class-dir` be exposed to users?

### ISSUE THREAD

**Issue by erp12** [seancorfield/build-clj#10]
Does it make sense to expose the default `target` and `class-dir` so that users can retrieve them in their on build steps?

Most users will probably use the sane defaults. Some users won't have any custom steps in their build and build-clj will allow them to never have to think about these defaults. That's great!

I have already found myself needing to insert a custom build step here or there in a couple projects. I still want to use the same values for `target` and `class-dir` (the build-clj defaults) but I need to access those values in my `build.clj`. There are currently 2 options:

1. Supply the `target` and `class-dir` values to build-clj and forgo the default, despite the fact that the supplied values are the same as the defaults. This seems like needless clutter in the user's build-clj.

2. Define a `target` and `class-dir` that is the same as the build-clj default values and only use them needed. This implicit coupling is brittle. Future versions of build-clj may change the defaults and break some build scripts. Also, it still clutters the user's build files with redundant information.

Alternatively, build-clj could expose the values of the default values such that users who elect to use the default can simply get the values from build-clj.

**Comment by seancorfield** [comment]
Sounds like a really good idea. I'll expose those functions with multiple arities (since, if you already know your `target` value, for example, you will just want to call `(default-target)` and not pass `nil` in).

**Comment by seancorfield** [comment]
v0.5.0 is available with these as public functions.
