### ISSUE TITLE
deps-deploy

### ISSUE THREAD

**Issue by masterbuilder99** [seancorfield/build-clj#12]
Hi Sean!

First, I would like to express my admiration for you. You did put in a lot of work into depstar.
It shows real character that you openly put depstar as depreciated given the features of tools deps.

I am using build-clj for my polilits I am building.  I believe you are aware of he breaking change
of tools.deps.alpha that occured on July 22, 2020 / 0.9.745 with removing tools.deps.alpha.reader.

I have noted that the current clojars version of deps-deploy  is very old, and predates the breaking
change of tools.deps.alpha.

Since you refer to this in build-clj I believe it could lead to strange error messages when using it
to build polyliths. I believe changing the dependency to the current github version would 
be much safer, as we can rule out a strange source of errors: 
io.github.slipset/deps-deploy {:git/sha "b4359c5d67ca002d9ed0c4b41b710d7e5a82e3bf"}

Thanks!

**Comment by seancorfield** [comment]
`build-clj` depends on `deps-deploy 0.2.0` which was released on September 17, 2021 and is based on `tools.deps.alpha 0.12.1036` which is from August 30, 2021. In addition, `build.clj` depends on `tools.build 0.6.5` which was released only nine days ago and depends on `tools.deps.alpha 0.12.1071` which is only thirteen days old.

I'm not sure why you think an outdated deps-deploy or t.d.a is in use?

**Comment by masterbuilder99** [comment]
That is very weird. I was running dep trees several times before making
this post.  Clojars confirms what you say.  :-) Perhaps a dependency
conflict in my config. I am sorry!
