### ISSUE TITLE
feature request: dump classes folder

### ISSUE THREAD

**Issue by masterbuilder99** [seancorfield/build-clj#13]
Hi!

Your build-clj is REALLY handy! I am changing my ci pipeline to use it. 

What I noticed is that for debugging purposes, I end up looking into my jar files with fastjar, to be sure
that what should get into the jar really gets into the jar.

It would be very nice, if you could add a  :debug-jar-classes-folder parameter, that would dump the 
content of the jar file into a folder. Inspecting a folder is much easier than extracting the jar content.

I thin this is a common pattern when writing a ci piepeline.

I hate changing my ci pipeline. It typically is a trial and error process. 
By having the capability to inspect the jar locally quickly, I believe it coul dbe much faster.

Thanks!

**Comment by seancorfield** [comment]
After running `jar` or `uber`, the contents of that file is available in the `target/classes` folder for inspection. Isn't that already what you want?

**Comment by masterbuilder99** [comment]
Yes this is exactly what you want. I wonder why I am not getting it. Will
investigate. Thanks

**Comment by seancorfield** [comment]
I'll leave this open for a while then.

**Comment by awb99** [comment]
It's working! Thanks a lot. Sometimes I dont see the forest in front of the trees.

**Comment by awb99** [comment]
You can close the tiket. I cannot as I am on another user right now. Thanks.
