### ISSUE TITLE
shadow-cljs problem with polyliths

### ISSUE THREAD

**Issue by awb99** [seancorfield/build-clj#14]
One thing that I noitced is with shadow-cljs deps.cljs files in in a polylith.
When there are multiple deps.cljs files in with local deps.edn dependencies, then EITHER shadow has a problem,
OR libraries that consume the JAR.

Because your the jar builder will override multiple deps.cljs files when they are directly in themain source folder of a project. If they are in a unique namespace, then shadow-cljs doesnot pick them up.

Not really related to build-clj. But since you are THE expert on this  manner, I thought I will post it here.

**Comment by seancorfield** [comment]
I've no idea what `deps.cljs` is but if you have multiple "things" on your classpath with identical filepaths, then only one of them is going to be visible -- whatever ends up first on the classpath. That's true of any resources in any context -- whether you're running from source with a classpath or whether you're using JAR files.
