### ISSUE TITLE
Exception when options map used in :main-opts when running another program

### ISSUE THREAD

**Issue by wardle** [seancorfield/build-clj#15]
In the documentation for eastwood, it [states](https://github.com/jonase/eastwood#depsedn) that one can include an options map. It works. For example, a fragment of a deps.edn file:

```
{:aliases {:lint/eastwood
           {:main-opts  ["-m" "eastwood.lint" {:source-paths ["src" "cmd"]}]
            :extra-deps {jonase/eastwood {:mvn/version "RELEASE"}}}}
```
This will run using clj -M:lint/eastwood.

However, this doesn't work when called using bb/run-task. e.g. from my build.clj file:

```
(defn lint [_]
  (bb/run-task {} [:lint/eastwood]))
```

```
$ clj -T:build lint

Running task for: eastwood
Execution error (ArrayStoreException) at java.lang.ProcessBuilder/start (ProcessBuilder.java:1085).
clojure.lang.PersistentArrayMap

Full report at:
/var/folders/w_/s108lpdd1bn84sntjbghwz3w0000gn/T/clojure-3128888617156774124.edn

```

It does work if I properly escape the options as per your documentation:

```
{:aliases {:lint/eastwood
                  {:main-opts  ["-m" "eastwood.lint" "{:source-paths,[\"src\"]}"]
                   :extra-deps {jonase/eastwood {:mvn/version "RELEASE"}}}
```

Escaping isn't much of an issue, but I'm unclear whether including an options map should be supported by build-clj, given it is supported by the clojure command line tooling? Actually, I find the [documentation](https://clojure.org/reference/deps_and_cli#_main_execution) on this a bit unclear.

Wasn't sure whether to raise this an an issue, or simply post on slack.

**Comment by seancorfield** [comment]
`clojure.main` -- and therefore `:main-opts` -- only accepts strings as arguments.

Per Eastwood's Usage docs -- https://github.com/jonase/eastwood#usage -- it shows that the EDN must be wrapped in double-quotes for main usage. I think their `deps.edn` example (with just `{}` without quotes) is wrong.

I suggest opening an issue against Eastwood to get clarification and/or fix their docs.

**Comment by wardle** [comment]
Thanks - will do! I would just note that not wrapping does actually work when using the clojure command line tooling - ie via clj -M -m ... - but perhaps it shouldn't! Thanks again.

**Comment by seancorfield** [comment]
Yes, because command line options are always strings but I would expect it to only work if you don't have spaces or special shell characters. Inside deps.edn {} is not a string.

**Comment by wardle** [comment]
Makes sense! Thanks again!
