### ISSUE TITLE
Could run-tests fallback to :exec-fn if one exists?

### ISSUE THREAD

**Issue by didibus** [seancorfield/build-clj#16]
`run-tests` runs the test using `:main-opts`, and if that's not there, it will assume a default test runner. But if there is an `:exec-fn` in the `:test` alias, could it not run that?

**Comment by seancorfield** [comment]
We have code at work to run exec functions but there are some serious problems with trying to do that and our code has some hacks in it that are not public-ready. I've created a JIRA about being able to exec things from `tools.build` but it doesn't seem to be a priority for the core team.

Remember that `run-tests` spins up a subprocess for this so the equivalent for exec fns needs to be able to leverage the `exec` JAR and that is currently very problematic.

If you don't want a subprocess running the exec fn, you can already call it directly from your `build.clj` script (and we do that for certain things) but then you don't get classpath isolation.
