### ISSUE TITLE
Default value for `:artifact` in `deploy` task does not respect `*project-root*`

### ISSUE THREAD

**Issue by steffan-westcott** [seancorfield/build-clj#18]
I have a multi-module project using `build-clj` (see [`build.clj`](https://github.com/steffan-westcott/clj-otel/blob/master/build.clj) file) which sets `*project-root*` before evaluating various build tasks in `build-clj`. The tasks `clean`, `jar` and `install` all work correctly, in particular they respect the current setting for `*project-root*`. This isn't surprising as this is a feature of `clojure.tools.build.api`.

However, I encountered an issue with the `deploy` task, in particular the setting for the `:artifact` option. `build-clj` currently defaults `:artifact` to the relative path from `*project-root*` of the JAR file to deploy, rather than the expected value which is the relative path from the current directory.

To be clear, I believe the setting of `:artifact` on [this line](https://github.com/seancorfield/build-clj/blob/1eeb2308977a792c85e45379417b6e2075a82767/src/org/corfield/build.clj#L297) isn't quite correct. The value of `jar-file` is correctly set, but is not necessarily the same as the expected value for `:artifact`. I believe this situation has arisen due to a mismatch in expected arguments between `clojure.tools.build.api` and `deps-deploy`, as the latter has no concept of `*project-root*`.

In my case, I worked around this issue by explicitly providing a value for `:artifact`, as can be seen here : https://github.com/steffan-westcott/clj-otel/blob/c2862459652d04b8a311bc742169b9b1b5167468/build.clj#L144

**Comment by seancorfield** [comment]
Probably the correct thing for me to do is call https://clojure.github.io/tools.build/clojure.tools.build.api.html#var-resolve-path on `jar-file` for that line.

**Comment by seancorfield** [comment]
You can try that out via `:git/sha "4d45fdd6c16a560a9d7112cfa4c7d4287dba2131"` (and no `:git/tag`) and let me know if that works for you?

**Comment by steffan-westcott** [comment]
@seancorfield Thank you for looking at this issue 🙂

I have [tried your fix](https://github.com/steffan-westcott/clj-otel/commit/c4de374fa897e070a46c0dc29b3ccd8ee77b8dd3) as suggested and [can confirm](https://github.com/steffan-westcott/clj-otel/actions/runs/1941178429) it is working as expected. Thanks for the prompt turnaround!

**Comment by seancorfield** [comment]
Thanks for testing it. I'll try to cut an official release today or tomorrow.
