### ISSUE TITLE
Should `deps.edn` be included in the jar file?

### ISSUE THREAD

**Issue by crinklywrappr** [seancorfield/build-clj#19]
I noticed that the `ci` function doesn't write gitlib dependencies to the POM file, but clj will download transitive gitlib dependencies by reading deps.edn.

This means that clj is unaware of transitive gitlib dependencies if I tell it to grab a library from clojars, for instance.

Is there some way to fix this?  In particular I'm curious if I should tell `bb/jar` to include `deps.edn` in the jar file.

**Comment by seancorfield** [comment]
Clojars, like Maven, is intended for JAR artifacts that have a `pom.xml` included -- and `pom.xml` cannot have dependencies on anything that isn't also a Clojars/Maven dependency.
