### ISSUE TITLE
jvm-opts on uber

### ISSUE THREAD

**Issue by mixedCase** [seancorfield/build-clj#7]
Is there any way to set up jvm-opts for an uberjar build?

I'm trying to move off depstar to this helper lib per the README's recommendation but neither passing `:compile-opts {:jvm-opts ["-Doption"]}` to opts nor `:jvm-opts ["-Doption"]` seem to work.

**Comment by seancorfield** [comment]
Per the readme:
```
As noted above, run-task takes an options hash map and a vector of aliases. The following options can be provided to run-task to override the default behavior:

:java-opts -- used instead of :jvm-opts from the aliases,
:jvm-opts -- used in addition to the :java-opts vector or in addition to :jvm-opts from the aliases,
:main -- used instead of 'clojure.main when building the java command to run,
:main-args -- used instead of :main-opts from the aliases,
:main-opts -- used in addition to the :main-args vector or in addition to :main-opts from the aliases.
```

**Comment by seancorfield** [comment]
See https://clojure.github.io/tools.build/clojure.tools.build.api.html#var-compile-clj

`:compile-opts` is a hash map of compiler options, not JVM flags.

**Comment by seancorfield** [comment]
If you can provide more detail about how you invoked `depstar`, I might be able to give you better guidance on how to invoke `tools.build` via `build-clj`.

**Comment by mixedCase** [comment]
@seancorfield Sorry, I'm probably missing something obvious, but my understanding of that readme snippet is that it was for the function `run-task`, not `uber`. Passing `jvm-opts` to `uber` is what I tried among other things.

This is my depstar alias:

```
:uberjar {:replace-deps {com.github.seancorfield/depstar {:mvn/version "2.1.278"}}
                     :exec-fn hf.depstar/uberjar
                     :exec-args {:jar "api.jar"
                                 :aot true
                                 :jvm-opts ["-Dmalli.registry/type=custom"]
                                 :main-class reverse.domain.application.core}
```

Thanks for such a quick response!

**Comment by seancorfield** [comment]
Ah, it turns out I was thinking about this https://ask.clojure.org/index.php/10894/create-basis-java-command-do-not-handle-jvm-opts which is about `java-command` (& `process`), not about `compile-clj`.

So you'll need to post on ask.clojure.org asking for `compile-clj` to support JVM options so that the core team can make a JIRA issue for it for tracking.

In the meantime, I guess you'll have to stay on `depstar` until that functionality is added to `compile-clj` (at which point, I'll expose it in `build-clj`).

**Comment by seancorfield** [comment]
https://ask.clojure.org/index.php/11078/tools-builds-compile-clj-does-not-allow-setting-jvm-options

Once TBUILD-18 is completed, I'll make sure `build-clj` supports it.

**Comment by seancorfield** [comment]
`tools.build`'s `compile-clj` supports `:java-opts` now and `build-clj` will just pass that straight through. I'll cut a new release of `build-clj` that depends on the latest `tools.build`.

**Comment by mixedCase** [comment]
@seancorfield Thank you for the fix and the heads up!

**Comment by seancorfield** [comment]
Well, I didn't have to fix anything 😄 I just waited for @puredanger to do his thing!
