### ISSUE TITLE
New: help task

### ISSUE THREAD

**Issue by pmonks** [seancorfield/build-clj#8]
When I am looking to interact at development-time with a `build-clj`-based project, I want to be able to run a "help" task that introspects that build and tells me what tasks that build script exposes, so I can operate the build script correctly without having to open it up and read it in detail.

**Comment by seancorfield** [comment]
I've updated the README to note that the following command is already built-in to the CLI/`deps.edn` system:

```bash
clojure -A:deps -T:build help/doc
```
